spring.application.name=SwiftRent

# Konfiguracja PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/swiftrent
spring.datasource.username=postgres
spring.datasource.password=student
spring.datasource.driver-class-name=org.postgresql.Driver

# Konfiguracja JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# waznosc tokenu tokenu w milisekundach (24 godziny)
jwt.expiration=86400000

# Server configuration
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# Logowanie
logging.level.ma.swiftrent=DEBUG
logging.level.org.springframework.security=DEBUG
